### ISSUE TITLE
Chests won't open

### ISSUE THREAD

**Issue by falko100** [1n9i9c7om/CATSBot#16]
Hey The chest logic has an issue.
The arrow has been patched out I think, so chests wont start the opening process automatically.

**Comment by p410n3** [comment]
Oh hey thanks for pointing that out! I actually stopped playing so I didn't even notice, (I dunno if 1n9i9c7om still plays). As he is the one doing the actual complex stuff I cant just help you tho. But I have informed him.

**Comment by 1n9i9c7om** [comment]
The arrows are still there for me, I've just tested that feature in the latest CATSBot Version as well as the latest CATS version:

    [20.06.17 15:37:12] Completed box found!
    [20.06.17 15:37:31] There's no box being unlocked right now, unlocking regular box
    [20.06.17 15:37:34] Finished ChestLogic!

It unlocked a finished wooden box and started a new one.

Is it simply not finding the unlocked chests or what's the issue? Keep in mind that it might be missing the arrows a few runs before it actually recognizes them, because the arrows are animated and the source image (the ingame screenshot) might be too different from the arrows we have screenshotted.

However, if it doesn't find the chests after, lets say 5 runs, there's probably something going wrong.

**Comment by falko100** [comment]
It is not opening a new chests after opening one when 2h passed.

Op 20 jun. 2017 15:40 schreef "Nico Meyer" <notifications@github.com>:

**Comment by p410n3** [comment]
Did you enable the option?
http://palone.top/sx/i/caa0bc7b019206aea175c52ced1b816c.png
Is your game on englisch and running on 720p?
Are you on v0.6?

Thts really all that comes to mind right now.

**Comment by falko100** [comment]
Yes to both.
So the bot should click a new chest when none are currently opening right ?

**Comment by 1n9i9c7om** [comment]
Yep. That's the expected behaviour.
I'll add some debug related stuff that might help to resolve this issue.

**Comment by falko100** [comment]
Seemed to be wrong version anyway. Downloaded it from the site.
After cloning it with git and building it, it works. Thanks for the help guys!
Awesome bot. I will try to help out on it 👍
