### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by bryan-kc** [1n9i9c7om/CATSBot#20]
Is this project still active and functioning?

Build instructions?

**Comment by p410n3** [comment]
This project is pretty much dead from our side (reffering to me and @1n9i9c7om, I was basically just FrontEnd anyways). We dont play the game anymore and our forum, which had quite a lot members was hacked. This marked the end of it pretty much. 

However there was one guy who heavily improved the Bots feature list and his version is more up to date. You can find it here: https://github.com/kunkliricsi/CATSBot2

Try to contact him.

For building, nothing special is needed. Open in it VS17 and press compile. 

If you dont have any more questions close the Issue please, otherwise feel free to ask further :)

Have a nice day :D

**Comment by 1n9i9c7om** [comment]
> For building, nothing special is needed. Open in it VS17 and press compile.

Make sure to restore NuGet packages though, we have 2 dependencies: MetroModernUI and AForge

**Comment by p410n3** [comment]
Whoopsie
